name: Update

on:
  workflow_dispatch:
  schedule:
    - cron:  12 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Compile
      run: npm run compile
    - name: Fetch latest data
      run: node update
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Latest data: $(date -u)" || exit 0
        git push
